export const FIGMA_ACTIVITY_DETAIL = {
  searchLabel: 'Scuba Diving',
  title: 'Scuba Diving in Kochi',
  locationLabel: 'Kochi - Kerala',
  rating: '4.5',
  customersLabel: '500+ customers',
  descriptionBlocks: [
    'Kochi is known for its picturesque seashores, backwaters, and rich maritime heritage. The calm coastal waters and vibrant marine life make it one of the most popular destinations for water adventures in Kerala.',
    'Scuba diving is a very popular tourist attraction in Kochi. Whether you are a first-time diver or an experienced explorer, guided sessions help you discover coral reefs, colourful fish, and unforgettable underwater landscapes.',
  ],
  highlightsTitle: 'Highlights',
  highlights: ['High Quality Equipments', 'Underwater Marine Creatures'],
  providesTitle: 'What we provide?',
  providesLink: 'View all ->',
  provides: [
    { id: 'diving', label: '50 Mins Scuba Diving', icon: 'water-outline' as const },
    { id: 'instructor', label: 'Certified Instructor', icon: 'person-outline' as const },
    { id: 'photos', label: 'Underwater Photos', icon: 'camera-outline' as const },
    { id: 'breakfast', label: 'Breakfast', icon: 'cafe-outline' as const },
  ],
  durationLabel: 'Half day / person',
  priceLabel: '₹ 4,564',
  taxLabel: 'including tax',
  cancellationText: 'Free Cancellation Before : 15-Jun-2026',
  primaryButtons: { contact: 'Contact Us', book: 'Book Now' },
  itineraryTitle: '1 day Itinerary',
  aboutActivityTitle: 'About the Activity',
  aboutActivitySubtitle: 'What will you experience',
  aboutActivityBodyIntro:
    'Kochi is known for its picturesque seashores, backwaters, and rich maritime heritage. Scuba diving is a very popular tourist attraction in Kochi, offering guided underwater experiences for beginners and certified divers alike.',
  aboutActivityBullets: [
    'Begin with a safety briefing and equipment orientation led by a certified PADI instructor.',
    'Practice basic breathing and movement techniques in shallow water before the open dive.',
    'Explore coral reefs and marine life during a guided 50-minute scuba session.',
    'Receive underwater photos and videos to capture your adventure.',
  ],
  thingsToCarryTitle: 'Things to Carry',
  thingsToCarry: [
    'Identification Documents',
    'Swimwear',
    'Towel & Sunscreen',
    'Medical Form',
    'Water Bottle',
    'Snacks',
    'One Pair of Dry Clothes',
    'UA Voucher',
  ],
  howToReachTitle: 'How To Reach',
  howToReach: [
    'By Air: Cochin International Airport (COK) is the closest airport, approximately 37.4 KM away. Taxis and app-based cabs are available from the airport to Kochi city and nearby dive centres.',
    'By Road: Kerala State Road Transport Corporation (KSRTC) operates frequent bus services to Kochi from Bangalore, Mysore, Chennai, and other major cities.',
    'By Train: Ernakulam Junction Railway Station (ERS) is well connected. Taxis and local transport are available from the station to the activity meeting point.',
  ],
  noteTitle: 'NOTE',
  noteBody:
    'Participants must be in good health and comfortable in water. Avoid heavy meals before diving. Follow all instructor safety guidelines during the session.',
  fullItineraryCta: 'Contact us for full itinerary',
  inclusionsTitle: 'Activity Inclusions',
  inclusions: [
    'Transportation from Selected Locations',
    'PADI Instructor',
    'upto 50 mins of diving',
    'Underwater Photos & Videos',
    'Training sessions are also available',
  ],
  exclusionsTitle: 'Activity Exclusions',
  exclusions: [
    'Expenses of a personal nature.',
    'Meals not mentioned in the itinerary or inclusions',
    'Travel Insurance',
    'Dinner',
    'Any Travel Expenses',
  ],
  footerText: [
    'GoTrip offers curated hotels, travel packages, exciting activities, and immersive glamping experiences — all blended into one seamless journey. Whether it’s a relaxing getaway, an adventurous escape, or a unique outdoor retreat, every option is carefully crafted to make your travels meaningful, personalized, and hassle‑free.',
    'From cozy stays to thrilling adventures under the stars, GoTrip ensures every trip resonates with your mood, style, and curiosity.',
  ].join('\n\n'),
};

export const FIGMA_ACTIVITY_EXPLORE = [
  {
    id: 'activity-explore-1',
    title: 'Paragliding in Varkala',
    location: 'Varkala - Kerala',
    rating: '4.6',
    price: '₹3650',
    priceSub: 'Half day / person',
    badge: 'ADVENTURE',
  },
  {
    id: 'activity-explore-2',
    title: 'Boat Trip in Alleppey',
    location: 'Alleppey - Kerala',
    rating: '4.4',
    price: '₹2850',
    priceSub: 'Half day / person',
    badge: 'ADVENTURE',
  },
  {
    id: 'activity-explore-3',
    title: 'Kayaking in Kochi',
    location: 'Kochi - Kerala',
    rating: '4.5',
    price: '₹2450',
    priceSub: 'Half day / person',
    badge: 'ADVENTURE',
  },
  {
    id: 'activity-explore-4',
    title: 'Snorkeling in Kovalam',
    location: 'Kovalam - Kerala',
    rating: '4.3',
    price: '₹3200',
    priceSub: 'Half day / person',
    badge: 'ADVENTURE',
  },
];
