export const FIGMA_GLAMPING_DETAIL = {
  searchLabel: 'Singapore',
  title: 'Base Camps, Sky Cottage, Rhodo Mansion',
  locationLabel: 'Munnar - Kerala',
  rating: '4.5',
  customersLabel: '500+ customers',
  descriptionBlocks: [
    'The Base Camp is located at an altitude of about 6,000 feet and serves as the starting hub for the entire experience. It is located roughly 24 km from Munnar town.  ',
    'The Experience: Classic outdoor camping. You stay in outdoor tents pitched amidst the cool mountain air, surrounded by tea gardens and shola forests.',
  ],
  highlightsTitle: 'Hightlights ',
  highlights: ['Sky Cottage', 'Base Camp', 'Rhodo Mansion'],
  providesTitle: 'What we provide?',
  providesLink: 'View all ->',
  provides: [
    { id: 'adventure', label: 'Adventure' },
    { id: 'privacy', label: 'Ultimate privacy' },
    { id: 'cuisine', label: 'Hot local cuisine' },
    { id: 'breakfast', label: 'Breakfast' },
  ],
  nightsLabel: '1 Nights / person',
  priceLabel: '₹ 4,564',
  taxLabel: 'including tax',
  cancellationText: 'Free Cancellation Before : 15-Jun-2026',
  primaryButtons: { contact: 'Contact Us', book: 'Book Now' },
  itineraryTitle: '4 day Itinerary',
  aboutCampingTitle: 'About the camping',
  aboutCampingSubtitle: 'What will you experience',
  aboutCampingBodyIntro:
    'The Base Camp is located at an altitude of about 6,000 feet and serves as the starting hub for the entire experience. It is located roughly 24 km from Munnar town.',
  aboutCampingBullets: [
    'The Experience: Classic outdoor camping. You stay in outdoor tents pitched amidst the cool mountain air, surrounded by tea gardens and shola forests.',
    'Vibe: Social and adventurous. It features a common campfire area where trekkers gather in the evening.',
    'Capacity: Can accommodate up to 40 people in tents.',
    'Best For: Budget travelers, backpackers, and large groups who love traditional camping.',
  ],
  thingsToCarryTitle: 'Things to Carry',
  thingsToCarry: [
    'Thermal inners (1 pair for sleeping)',
    'Heavy jacket (Fleece, down jacket, or windbreaker; it gets freezing at night)',
    'Trek pants & quick-dry T-shirts (Avoid jeans)',
    'Trekking shoes (Sturdy with good grip for steep, rocky terrain)',
    'Small daypack (To carry water and snacks during the actual hike)',
    'Headlamp or Flashlight (Mandatory for the pitch-dark 4:30 AM sunrise climb)',
    'Raincoat or Poncho (Mountain weather is highly unpredictable)',
  ],
  howToReachTitle: 'How To Reach',
  howToReach: [
    'By Air: Cochin International Airport (COK) is the closest airport (~110–120 km away). You can hire a pre-paid taxi or take a state bus (KSRTC) from the airport or nearby Angamaly to Munnar.',
    'By Rail: Aluva Railway Station (~110 km) or Ernakulam Junction (~125 km) are the closest railheads. KSRTC buses run frequently from outside these stations directly to Munnar.',
    'By Road: Frequent public and private buses connect Munnar to cities like Kochi, Madurai, Coimbatore, and Bangalore.',
  ],
  noteTitle: 'NOTE',
  noteBody:
    'Up at Rhodo Valley (Sky Cottage and Rhodo Mansion), there is virtually no cellular network or internet. Electricity is limited (solar), and the weather gets incredibly cold.',
  fullItineraryCta: 'Contact us for full itinerary',
  inclusionsTitle: 'Camping Inclusions',
  inclusions: [
    'Accommodation: Tents (Base Camp), Sky Cottage, or Rhodo Mansion rooms.',
    'All Meals: Day 1 evening tea, buffet dinner; Day 2 morning tea, breakfast, and packed lunch.',
    'Permits: All mandatory Forest Department entry fees and trekking passes.',
    'Trek Guide: A compulsory, certified local KFDC guide for the summit climb.',
    'Jeep Transfers: 4x4 off-road jeep rides from the main entry checkpoint to your stay and back.',
    'Campfire: Evening campfire session (strictly weather-dependent).',
  ],
  exclusionsTitle: 'Camping Exclusions',
  exclusions: [
    'Transport to Munnar: Your travel from your hometown to Munnar.',
    'Transport to KFDC Office: Getting yourself to the Munnar town KFDC check-in point.',
    'Personal Gear: Hiking shoes, backpacks, torches, raincoats, or warm jackets.',
    'Porter Service: You must carry your own personal backpack to your tent/room.',
    'Alcohol & Cigarettes: Strictly banned by the Forest Department.',
    'Tips & Insurance: Optional tips for guides/drivers and personal medical insurance.',
  ],
  footerText: [
    'GoTrip offers curated hotels, travel packages, exciting activities, and immersive glamping experiences — all blended into one seamless journey. Whether it’s a relaxing getaway, an adventurous escape, or a unique outdoor retreat, every option is carefully crafted to make your travels meaningful, personalized, and hassle‑free.',
    'From cozy stays to thrilling adventures under the stars, GoTrip ensures every trip resonates with your mood, style, and curiosity.',
  ].join('\n\n'),
};

export const FIGMA_GLAMPING_EXPLORE = [
  {
    id: 'glamping-explore-1',
    title: 'Base Camps, Sky Cottage, Rhodo Mansion',
    location: 'Munnar - Kerala',
    rating: '4.5',
    price: '₹4650',
    priceSub: 'Per night / person',
    badge: 'COUPLE FRIENDLY',
  },
  {
    id: 'glamping-explore-2',
    title: 'Base Camps, Sky Cottage, Rhodo Mansion',
    location: 'Munnar - Kerala',
    rating: '4.5',
    price: '₹4650',
    priceSub: 'Per night / person',
    badge: 'COUPLE FRIENDLY',
  },
  {
    id: 'glamping-explore-3',
    title: 'Base Camps, Sky Cottage, Rhodo Mansion',
    location: 'Munnar - Kerala',
    rating: '4.5',
    price: '₹4650',
    priceSub: 'Per night / person',
    badge: 'COUPLE FRIENDLY',
  },
  {
    id: 'glamping-explore-4',
    title: 'Base Camps, Sky Cottage, Rhodo Mansion',
    location: 'Munnar - Kerala',
    rating: '4.5',
    price: '₹4650',
    priceSub: 'Per night / person',
    badge: 'COUPLE FRIENDLY',
  },
];
